env:
  global:
  - secure: "Ja4fsh6GHywIxlgMDWg5LwmRPkbph0AyhgoEZSme3kGpU3KNc6dze5w5GL98b4DNNil/x3ziTzCK8zUe8+G6oSHtHWjYGgaXFILd2ICz2O8CmDTl6K5Mm3k4/lois9xZbmpa/CvZwsmOeaAIF7oCgSErzrRfzLZ3a/zUwsmzJQw="

language: cpp
compiler:
  - clang

before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update
  - sudo apt-get install cmake
  - sudo apt-get install -qq wget liblua5.1-dev libluajit-5.1-dev boost1.55
  - mkdir -pv build

before_script:
  cd build && LDFLAGS="-lrt" cmake -DENABLE_LUA=on -DENABLE_PYTHON=on -DENABLE_ZMQ=ON ..

script:
  make -j3

notifications:
  recipients:
    - microcaicai@gmail.com
    - jack.wgm@gmail.com
  email:
    on_success: change
    on_failure: always


addons:
  coverity_scan:
    project:
      name: "avplayer/avbot"
      description: "Build submitted via Travis CI"
    notification_email: microcaicai@gmail.com
    build_command_prepend: "cmake . ; make clean"
    build_command:   "make -j2"
    branch_pattern: coverity_scan
